name       : ruby-win32-file-security
version    : 1.0.10
release    : 4
source     :
    - https://rubygems.org/downloads/win32-file-security-1.0.10.gem : 39e528fc28e8f11e5132db1c6fc93bc7c22f232783953841ad3dc3a08240f852
license    : Artistic-2.0
component  : programming.ruby
summary    : RubyGem - win32-file-security
description: |
    Ruby library that extends the File class with security related methods for MS Windows
builddeps  :
    - pkgconfig(ruby-2.7)
rundeps    :
    - ruby-ffi
    - ruby-ffi-win32-extensions
install    : |
    %gem_install
    rm -rf $installdir/$geminstalldir/{build_info,doc,extensions}
